config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show, :index]

  resources :posts

  resources :comments, only: [:show, :create] do
    get "reply" => "comments#new", as: :reply_comment
  end

  resources :votes, only: [:create, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :submitter,
             class_name:  :User,
             foreign_key: :user_id

  belongs_to :commentable,
             polymorphic: true

  has_many :comments,
           as:        :commentable,
           dependent: :destroy

  has_many :votes,
           as:        :voteable,
           dependent: :destroy         

  validates :text,
            presence: { message: "The comment you submitted was blank" }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :submitter,
             class_name:  :User,
             foreign_key: :user_id

  has_many :comments,
           as:        :commentable,
           dependent: :destroy

  has_many :votes,
           as:        :voteable,
           dependent: :destroy

  validates :title, :url,
            presence: true,
            if:       :url_post?

  validates :title, :url,
            absence: true,
            if:      :text_post?

  validate :at_least_one_field_present
  validate :a_post_can_only_be_one_type

  def type
    if url_post?
      "url"
    else
      "text"
    end
  end

  def url_post?
    url.present? || title.present?
  end

  def text_post?
    text.present?
  end

  private

  def a_post_can_only_be_one_type
    if text_post? && url_post?
      errors.add(:base, "You may submit either text content OR a url link, NOT both")
    end
  end

  def at_least_one_field_present
    if text.blank? && url.blank? && title.blank?
      errors.add(:base, "You must submit a url link OR text content")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Other available devise modules:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :voter,
             class_name:  :User,
             foreign_key: :user_id

  belongs_to :voteable,
             polymorphic: true

  validates :user_id,
            uniqueness: { scope: [:voteable_id, :voteable_type] }

  validates :value,
            presence: true,
            inclusion: { in: [1, -1] }

  def vote_type
    if value == 1
      "up"
    else
      "down"
    end
  end

  def up_vote?
    vote_type == "up"
  end

  def down_vote?
    vote_type == "down"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = %i[name about]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  def authenticate_to_submit
    if !user_signed_in?
      flash[:alert] = "You must be logged in to submit a post or comment"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentableController

  before_action :authenticate_user!, only: :create
  before_action :authenticate_to_submit, only: :new

  helper_method :comment

  def new
  end

  def create
    new_comment = current_user.comments.build(comment_params)
    commentable = new_comment.commentable
    commentable_owner = User.find(commentable.user_id)

    if new_comment.save
      UserMailer.comment_notification(commentable_owner).deliver_now
      redirect_to commentable
    else
      message = new_comment.errors.messages[:text].join(", ")
      if commentable.kind_of?(Post)
        flash[:inline] = message
        redirect_to commentable
      else
        flash.now[:inline] = message
        render :new
      end
    end
  end

  def show
  end

  private

  def comment
    @comment ||= Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(
      :text,
      :commentable_type,
      :commentable_id
    )
  end
end

app/controllers/concerns/commentable_controller.rb
module CommentableController
  def self.included(base)
    base.helper_method :commentable
  end

  def controller
    params[:controller]
  end

  def id_finder
    /[a-zA-Z]+_id/.match(params.to_s).to_s
  end

  def commentable_type
    controller.classify.constantize
  end

  def id
    if commentable_type == Post
      params[:id]
    elsif params[id_finder].present?
      params[id_finder]
    else
      params[controller.singularize][id_finder]
    end
  end

  def commentable
    commentable_type.find(id)
  end
end

app/controllers/concerns/voteable_controller.rb
# module VoteableController
#   extend ActiveSupport::Concern
#
#   def self.included(base)
#     base.helper_method :parents_vote
#   end
#
#   def parents_vote(parent)
#     @vote = Vote.find_by(user_id: current_user, voteable_id: parent)
#   end
# end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

  private

  def after_confirmation_path_for(resource_name, resource)
    new_user_session
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include CommentableController

  before_action :authenticate_user!, only: :create
  before_action :authenticate_to_submit, only: :new

  helper_method :posts, :post

  def new
    @post = Post.new
  end

  def show
  end

  def index
  end

  def create
    @post = Post.new(post_params.merge(submitter: current_user))
    
    if @post.save
      flash[:alert] = "Your post was saved"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  private

  def posts
    @posts ||= Post.all
  end

  def post
    @post ||= Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :text)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_inactive_sign_up_path_for(resource)
    users_path
  end

  def update_resource(user, params)
    user.update_without_password(params)
  end

  def after_update_path_for(user)
    user_path(user.name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  private

  def user
    @user ||= User.find_by(name: params[:id])
  end
  helper_method :user

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  helper_method :vote, :parent

  def create
    @vote = current_user.votes.create(vote_params)

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
      format.json { render json: @vote, status: :created }
    end
  end

  def update
    vote.update(value: vote_params[:value])

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
      format.json { render json: vote, status: :updated }
    end
  end

  def destroy
    vote.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
      format.json { render json: vote, status: :deleted }
    end
  end

  private

  def parent
    @parent = @vote.voteable
  end

  def vote
    @vote ||= Vote.find(params[:id])
  end

  def vote_params
    params.require(:vote).permit(:voteable_type, :voteable_id, :value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_errors_on_base(resource, field_name)
    if resource.errors.any? && resource.errors.messages[field_name].present?
      content_tag(:div, resource.errors.full_messages_for(field_name).join(", "), class: "alert alert-alert")
    end
  end

  def show_errors_inline(resource, field_name)
    if resource.errors.any? && resource.errors.full_messages_for(field_name).present? && !resource.errors[:base].present?
      content_tag(:div, resource.errors.full_messages_for(field_name).join(", "), class: "alert alert-alert inline-alert")
    end
  end

  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
  end
end

app/views/comments/new.html.erb
<p>
  <%= commentable.text %>
  <br />
  <%= " - contributed by #{commentable.submitter.name}" %>
</p>
<%= render partial: "shared/comment/form_new",
                    locals: { submit_text: "Submit Reply" }  %>

app/views/comments/show.html.erb
<%= render partial: "shared/comment/details", locals: { comment: comment } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyHackerNewsLite</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= favicon_link_tag asset_path("favicon.ico"), rel: :icon, type: "image/x-icon" %>
  </head>
  <body>
    <nav>
      <div class="nav_always_show">
        <%= image_tag "my_HN_lite.png" %>
        <span><%= link_to "MyHackerNewsLite", root_path %></span>
        <span><%= link_to "Submit", new_post_path %></span>
      </div>
      <% if user_signed_in? %>
        <div class="nav_conditional_show">
          <p>Welcome, <%= link_to(current_user.name.titleize, user_path(current_user.name)) %>
             | <%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
        </div>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %>
      <% end %>
    </nav>
    <% flash.each do |type, msg| %>
      <% if type.to_s != "inline" %>
        <%= content_tag(:div, msg, class: "alert alert-#{type}") %>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_comment.html.erb
<%= comment.text %>
<%= link_to "Reply to #{comment.submitter.name}", post_comment_reply_path(post.id, comment.id) %>
<br />
<% if comment.comments.exists? %>
    <div class="replies-posted">
      <% comment.comments.each do |reply_comment| %>
        <%= render partial: "comment", locals: { comment: reply_comment } %>
      <% end %>
  </div>
<% end %>

app/views/posts/_input.html.erb
<div class="tabbed">
  <%= form.label(field_name) %>
  <% if field_name == :text %>
    <%= form.text_area(field_name) %>
  <% else %>
    <%= form.text_field(field_name) %>
  <% end %>
</div>
<%= show_errors_inline(post, field_name) %>

app/views/posts/_post.html.erb
<div class="show_and_edit">
  <table>
    <thead>
      <tr class="table_headers">
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% if post.url_post? %>
        <tr>
          <td scope="row">title:</td>
          <td class="col2"><%= post.title.titleize %></td>
        </tr>
        <tr>
          <td scope="row">link:</td>
          <td class="col2"><%= link_to(nil, post.url) %></td>
        </tr>
      <% else %>
        <tr>
          <td scope="row">text:</td>
          <td class="col2"><%= post.text %></td>
        </tr>
      <% end %>
      <tr>
        <td scope="row">contributer:</td>
        <td class="col2"><%= post.submitter.name %></td>
      </tr>
      <tr>
        <td scope="row">submitted at:</td>
        <td class="col2"><%= time_ago_in_words(post.created_at) %> ago</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/posts/_post_presenter.html.erb
<div>
  <% if post.url_post? %>
    <span><%= link_to(post.title, post.url) %></span>
  <% else %>
    <span><%= post.text.truncate(80, {separator: " "}) %></span>
  <% end %>
  <p>by <%= link_to(post.submitter.name, user_path(post.submitter.name)) %> | posted <%= link_to(time_ago_in_words(post.created_at), post) %>  ago
  </p>
</div>

app/views/posts/_post_presenter_index.html.erb
<div>
  <%= render partial: "#{post.type}_post_template", locals: { post: post } %>
  <p>by <%= link_to(post.submitter.name, user_path(post.submitter.name)) %> | posted <%= link_to(time_ago_in_words(post.created_at), post) %>  ago
  </p>
</div>

app/views/posts/_post_presenter_show.html.erb
<div class="show_and_edit">
  <table>
    <thead>
      <tr class="table_headers">
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% if post.url_post? %>
        <tr>
          <td scope="row">title:</td>
          <td class="col2"><%= post.title.titleize %></td>
        </tr>
        <tr>
          <td scope="row">link:</td>
          <td class="col2"><%= link_to(nil, post.url) %></td>
        </tr>
      <% else %>
        <tr>
          <td scope="row">text:</td>
          <td class="col2"><%= post.text %></td>
        </tr>
      <% end %>
      <tr>
        <td scope="row">contributer:</td>
        <td class="col2"><%= post.submitter.name %></td>
      </tr>
      <tr>
        <td scope="row">submitted at:</td>
        <td class="col2"><%= time_ago_in_words(post.created_at) %> ago</td>
      </tr>
    </tbody>
  </table>
  <br />
  <div class="center_votes">
    <p>
      Voting options
    </p>
    <div class="vote_wrapper_comment" id="vote_wrapper_<%= post.id %>" >
      <%= render partial: "shared/vote/presenter_index", locals: { parent: post } %>
    </div>
  </div>
</div>

app/views/posts/_text_post_template.html.erb
<span><%= post.text.truncate(60, {separator: " "}) %></span>

app/views/posts/_url_post_template.html.erb
<span><%= link_to(post.title.truncate(60, {separator: " "}), post.url) %></span>

app/views/posts/index.html.erb
<% posts.each do |post| %>
  <br />
  <div class="vote_and_post_wrapper">
    <div class="vote_wrapper" id="vote_wrapper_<%= post.id %>" >
      <%= render partial: "shared/vote/presenter_index", locals: { parent: post } %>
    </div>
    <%= render partial: "post_presenter_index", locals: { post: post } %>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="show_and_edit">
  <%= form_for post do |f| %>
    <%= show_errors_on_base(post, :base) %>
    <%= render partial: "input", locals: { form: f, field_name: :title } %>
    <%= render partial: "input", locals: { form: f, field_name: :url } %>
    <p class="center">OR</p>
    <%= render partial: "input", locals: { form: f, field_name: :text } %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render partial: "post_presenter_show" %>
<%= render partial: "shared/comment/form_new",
                    locals: { submit_text: "Comment On Post" }  %>
<% if post.comments.exists? %>
  <div class="comments-posted">
    <% post.comments.each do |direct_comment| %>
      <% if direct_comment.id.present? %>
        <%= render partial: "shared/comment/details",
                            locals: { comment: direct_comment } %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="profile_show_and_edit">
  <h1>Profile</h1>
  <div class="tabbed">
    <div class="label">user:</div>
    <div><%= @profiled_user.name %></div>
  </div>
  <div class="tabbed">
    <div class="label">created:</div>
    <div><%= @profiled_user.created_at %></div>
  </div>
  <div class="tabbed">
    <div class="label">karma:</div>
    <div>TBD</div>
  </div>
  <div class="tabbed">
    <div class="label">about:</div>
    <div><%= @profiled_user.about %></div>
  </div>
  <div class="tabbed">
    <div class="label">email:</div>
    <div><%= @profiled_user.email %></div>
  </div>
  <div class="tabbed">
    <div class="label">created:</div>
    <div><%= @profiled_user.created_at %></div>
  </div>
</div>

app/views/shared/_comment.html.erb
<%= comment.text %>
<% if user_signed_in? %>
  <%= link_to "Reply to #{comment.submitter.name}", comment_reply_path(comment) %>
<% else %>
  <%= link_to " - contributed by #{comment.submitter.name}", user_path(comment.submitter.name) %>
<% end %>
<div class="vote_wrapper_comment" >
  <div class="vote_count_comment">
    <%= (comment&.votes.present?) ? comment&.votes.sum(:value) : nil %>
  </div>
  <%= render partial: "shared/vote/presenter_index", locals: { parent: comment } %>
</div>
<br />
<% if comment.comments.exists? %>
  <div class="replies-posted">
    <% comment.comments.each do |reply_comment| %>
      <%= render partial: "shared/comment", locals: { comment: reply_comment } %>
    <% end %>
  </div>
<% end %>

app/views/shared/_delete_vote.html.erb
<%= link_to vote, method: :delete, id: "delete" do %>
    <i class="fa fa-times-circle clickable"></i>
<% end %>

app/views/shared/_edit_vote.html.erb
<%= form_for(vote, url: vote_path(vote), action: "update") do |f| %>
  <%= f.button type: 'submit', class: "my-button clickable", id: vote_type do %>
    <%= tag.i class: "fa fa-chevron-circle-#{vote_type}" %>
  <% end %>
<% end %>

app/views/shared/_form.html.erb
<%= form.text_area :text %>
<br />
<% flash.each do |type, msg| %>
  <% if type.to_s == "inline" %>
    <%= content_tag(:div, msg, class: "alert alert-alert alert-inline") %>
  <% end %>
<% end %>

app/views/shared/_new_comment.html.erb
<%= form.text_area :text %>
<br />
<% flash.each do |type, msg| %>
  <% if type.to_s == "inline" %>
    <%= content_tag(:div, msg, class: "alert alert-alert alert-inline") %>
  <% end %>
<% end %>

app/views/shared/_new_vote.html.erb
<%= form_for(new_vote, url: votes_path, action: "create") do |f| %>
  <%= f.hidden_field :voteable_type, value: parent.class %>
  <%= f.hidden_field :voteable_id, value: parent.id %>
  <%= f.hidden_field :value, value: one %>
  <%= f.button type: 'submit', class: "my-button clickable", id: vote_type do %>
    <%= tag.i class: "fa fa-chevron-circle-#{vote_type}" %>
  <% end %>
<% end %>

app/views/shared/_vote_form.html.erb
<%= form_for(new_vote, url: votes_path, action: "create") do |f| %>
  <%= f.hidden_field :voteable_type, value: post.class %>
  <%= f.hidden_field :voteable_id, value: post.id %>
  <%= f.hidden_field :value, value: one %>
  <%= f.button type: 'submit', class: "button my-button", id: direction do %>
    <%= tag.i class: "fa fa-chevron-circle-#{direction}" %>
  <% end %>
<% end %>

app/views/shared/_vote_icons.html.erb
<div class="vote_button_wrapper">
  <i class="fa fa-chevron-circle-up not-clickable"></i>
  <i class="fa fa-chevron-circle-down not-clickable"></i>
  <i class="fa fa-times-circle not-clickable"></i>
</div>

app/views/shared/_vote_static_icons.html.erb
<div class="vote_button_wrapper">
  <i class="fa fa-chevron-circle-up not-clickable"></i>
  <i class="fa fa-chevron-circle-down not-clickable"></i>
  <i class="fa fa-times-circle not-clickable"></i>
</div>

app/views/shared/comment/_details.html.erb
<% present comment do |presenter| %>

  <%= presenter.text %>
  <%= presenter.attribution_link %>

  <div class="vote_wrapper_comment" id="vote_wrapper_<%= presenter.id %>" >
    <%= render partial: "shared/vote/presenter_index",
                        locals: { parent: comment } %>
  </div>

  </br >

  <% if presenter.replies? %>
    <div class="replies-posted">
      <% presenter.replies.each do |reply_comment| %>
        <%= render partial: "shared/comment/details",
                            locals: { comment: reply_comment } %>
      <% end %>
    </div>
  <% end %>

<% end %>

app/views/shared/comment/_form_new.html.erb
<%= form_for(commentable.comments.build) do |form| %>
  <%= form.hidden_field :commentable_type %>
  <%= form.hidden_field :commentable_id %>
  <%= form.text_area :text %>
  <br />
  <% flash.each do |type, msg| %>
    <% if type.to_s == "inline" %>
      <%= content_tag(:div, msg, class: "alert alert-alert alert-inline") %>
    <% end %>
  <% end %>
  <%= form.submit submit_text %>
<% end %>

app/views/shared/comment/_presenter.html.erb
<% present comment do |comment_presenter| %>

  <%= comment_presenter.text %>
  <%= comment_presenter.text_trailer %>

  <%= tag.div class: "vote_wrapper_comment" do %>
    <%= tag.div class: "vote_count_comment" do %>
      <%= comment_presenter.sum %>
    <% end %>
    <%= render partial: "shared/vote/presenter_index",
                        locals: { parent: comment } %>
  <% end %>

  <%= tag.br %>

  <% if comment_presenter.replies? %>
    <%= tag.div class: "replies-posted" do %>
      <% comment_presenter.replies.each do |reply_comment| %>
        <%= render partial: "shared/comment/presenter",
                            locals: { comment: reply_comment } %>
      <% end %>
    <% end %>
  <% end %>

<% end %>

app/views/shared/comment/_show_partial.html.erb
<% present comment do |presenter| %>

  <%= presenter.text %>
  <%= presenter.attribution_link %>

  <div class="vote_wrapper_comment">
    <div class="vote_count_comment">
      <%= presenter.sum %>
    </div>
    <%= render partial: "shared/vote/presenter_index",
                        locals: { parent: comment } %>
  </div>

  </br >

  <% if presenter.replies? %>
    <div class="replies-posted">
      <% presenter.replies.each do |reply_comment| %>
        <%= render partial: "shared/comment/show_partial",
                            locals: { comment: reply_comment } %>
      <% end %>
    </div>
  <% end %>

<% end %>

app/views/shared/vote/_cancel.html.erb
<%= link_to vote, method: :delete, id: "delete" do %>
  <%= tag.i class: "fa fa-times-circle clickable" %>
<% end %>

app/views/shared/vote/_delete.html.erb
<%= link_to vote, method: :delete, id: "delete", remote: true do %>
  <i class="fa fa-times-circle clickable"></i>
<% end %>

app/views/shared/vote/_down.html.erb
<%= form_for vote, remote: true do |f| %>
  <%= f.hidden_field :voteable_type %>
  <%= f.hidden_field :voteable_id %>
  <%= f.hidden_field :value, value: -1 %>
  <%= f.button type: 'submit', class: "my-button clickable", id: "down" do %>
    <i class="fa fa-chevron-circle-down"></i>
  <% end %>
<% end %>

app/views/shared/vote/_edit_buttons.html.erb
<%= form_for(parents_vote(parent), url: vote_path(parents_vote(parent)), action: "update") do |f| %>
  <%= f.hidden_field :value, value: 1 %>
  <%= f.button type: 'submit', class: "my-button clickable", id: "up", disabled: parents_vote(parent)&.up_vote? do %>
    <%= tag.i class: "fa fa-chevron-circle-up" %>
  <% end %>
<% end %>
<%= form_for(parents_vote(parent), url: vote_path(parents_vote(parent)), action: "update") do |f| %>
  <%= f.hidden_field :value, value: -1 %>
  <%= f.button type: 'submit', class: "my-button clickable", id: "down", disabled: parents_vote(parent)&.down_vote? do %>
    <%= tag.i class: "fa fa-chevron-circle-down" %>
  <% end %>
<% end %>

app/views/shared/vote/_new_buttons.html.erb
<%= form_for parent.votes.build(value: 1) do |f| %>
  <%= f.hidden_field :voteable_type %>
  <%= f.hidden_field :voteable_id %>
  <%= f.hidden_field :value %>
  <%= f.button type: 'submit', class: "my-button clickable", id: "up" do %>
    <%= tag.i class: "fa fa-chevron-circle-up" %>
  <% end %>
<% end %>
<%= form_for parent.votes.build(value: -1) do |f| %>
  <%= f.hidden_field :voteable_type %>
  <%= f.hidden_field :voteable_id %>
  <%= f.hidden_field :value %>
  <%= f.button type: 'submit', class: "my-button clickable", id: "down" do %>
    <%= tag.i class: "fa fa-chevron-circle-down" %>
  <% end %>
<% end %>

app/views/shared/vote/_presenter_index.html.erb
<div class="vote_count" >
  <%= parent.votes.sum(:value) %>
</div>
<% present parent, VoteButtonPresenter do |presenter| %>
  <div class="vote_button_wrapper" id="vote_wrapper_<%= presenter.id %>" >
    <%= presenter.buttons %>
  </div>
<% end %>

app/views/shared/vote/_static_icons.html.erb
<i class="fa fa-chevron-circle-up not-clickable"></i>
<i class="fa fa-chevron-circle-down not-clickable"></i>
<i class="fa fa-times-circle not-clickable"></i>

app/views/shared/vote/_up.html.erb
<%= form_for vote, remote: true do |f| %>
  <%= f.hidden_field :voteable_type %>
  <%= f.hidden_field :voteable_id %>
  <%= f.hidden_field :value, value: 1 %>
  <%= f.button type: 'submit', class: "my-button clickable", id: "up" do %>
    <i class="fa fa-chevron-circle-up"></i>
  <% end %>
<% end %>

app/views/submissions/_input.html.erb
<div class="tabbed">
  <%= form.label(field_name) %>
  <% if field_name == :text %>
    <%= form.text_area(field_name) %>
  <% else %>
    <%= form.text_field(field_name) %>
  <% end %>
</div>
<%= show_errors_inline(new_submission, field_name) %>

app/views/submissions/show.html.erb
<div class="show_and_edit">
  <table>
    <thead>
      <tr class="table_headers">
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% if post.url_post_submission? %>
        <tr>
          <td scope="row">title:</td>
          <td class="col2"><%= post.title.titleize %></td>
        </tr>
        <tr>
          <td scope="row">link:</td>
          <td class="col2"><%= link_to post.url %></td>
        </tr>
      <% else %>
        <tr>
          <td scope="row">text:</td>
          <td class="col2"><%= post.text %></td>
        </tr>
      <% end %>
      <tr>
        <td scope="row">contributer:</td>
        <td class="col2"><%= post.user.name %></td>
      </tr>
      <tr>
        <td scope="row">submitted at:</td>
        <td class="col2"><%= time_ago_in_words(post.created_at) %> ago</td>
      </tr>
    </tbody>
  </table>
</div>
<div class="comments-posted">
  <% if post.comments.exists? %>
    <% post.comments.each do |c| %>
      <%= "comment by #{c.user.name}: #{c.text}" %>
      <br />
    <% end %>
  <% end %>
</div>
<%= form_for(comment, url: submission_comments_path, method: :post) do |f| %>
  <%= f.text_area :text, cols: 60 %>
  <br />
  <%= f.hidden_field :post_id, :value => parent_id %>
  <% flash.each do |type, msg| %>
    <% if type.to_s == "inline" %>
      <%= content_tag(:div, msg, class: "alert alert-alert alert-inline") %>
    <% end %>
  <% end %>
  <%= f.submit "add comment" %>
<% end %>

app/views/users/show.html.erb
<div class="show_and_edit">
  <h1>Profile</h1>
  <div class="tabbed">
    <div class="label">user:</div>
    <div><%= user.name %></div>
  </div>
  <div class="tabbed">
    <div class="label">created:</div>
    <div><%= time_ago_in_words(user.created_at) %> ago</div>
  </div>
  <div class="tabbed">
    <div class="label">karma:</div>
    <div>TBD</div>
  </div>
  <div class="tabbed">
    <div class="label">about:</div>
    <div><%= user.about %></div>
  </div>
  <div class="tabbed">
    <div class="label">email:</div>
    <div><%= mail_to(user.email) %></div>
  </div>
</div>

app/views/votes/create.js.erb
<% parent_div = "#vote_wrapper_#{parent.id}" %>
$("<%= j parent_div %>").html("<%= j (render '/shared/vote/presenter_index') %>")

app/views/votes/destroy.js.erb
<% parent_div = "#vote_wrapper_#{parent.id}" %>
$("<%= j parent_div %>").html("<%= j (render '/shared/vote/presenter_index') %>")

app/views/votes/update.js.erb
<% parent_div = "#vote_wrapper_#{parent.id}" %>
$("<%= j parent_div %>").html("<%= j (render '/shared/vote/presenter_index') %>")